### ISSUE TITLE
please update docu as CLI binary release assets are no longer zipped

### ISSUE THREAD

**Issue by dorn-gerhard** [Unity-Technologies/unity-gaming-services-cli#1]
the current docu in https://services.docs.unity.com/guides/ugs-cli/latest/general/samples/ci-cd-pipeline-usage/github-actions/ refers to zips

**Comment by yoan-bernatchez** [comment]
Apologies for the outdated content, this will be updated with the next release 🙂
Thank you for reporting!

**Comment by yoan-bernatchez** [comment]
Fixed with 1.1.0 release
