### ISSUE TITLE
Import Remote Config using UGS CLI - System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by teodorplop** [Unity-Technologies/unity-gaming-services-cli#5]
- name: Export Remote Config from Develop Environment
    run: |
      chmod +x ./ugs-linux-x64
      ./ugs-linux-x64 remote-config export . develop_config.rczip -p $UGS_CLI_PROJECT_ID -e develop

  - name: Import Remote Config into Feature Environment
    run: |
      chmod +x ./ugs-linux-x64
      ./ugs-linux-x64 remote-config import . develop_config.rczip -p $UGS_CLI_PROJECT_ID -e ${{ env.ENVIRONMENT }}

I'm using a simple command to export & import remote config keys from one environment to another. However, it fails with an error if the environment is fresh and doesn't contain any keys. 

> Importing your environment...
> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
>   at void System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument  
>      argument)                                                                  
>   at IEnumerable<TResult> System.Linq.Enumerable.Select<TSource,TResult>(       
>      IEnumerable<TSource> source, Func<TSource, TResult> selector)              
>   at IReadOnlyList<RemoteConfigEntryDTO>                                        
>      Unity.Services.Cli.RemoteConfig.Handlers.ExportImport.RemoteConfigImporter.
>      ToDto(IReadOnlyList<RemoteConfigEntry> entries)                            
>   at async Task<IEnumerable<RemoteConfigEntryDTO>>                              
>      Unity.Services.Cli.RemoteConfig.Handlers.ExportImport.RemoteConfigImporter.
>      ListConfigsAsync(string cloudProjectId, string environmentId,              
>      CancellationToken cancellationToken)                                       
>   at async Task Unity.Services.Cli.Authoring.Import.BaseImporter`1.ImportAsync( 
>      ImportInput input, CancellationToken cancellationToken, int                
>      maxParallelTaskLimit)                                                      
>   at void Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.     
>      MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:79              
>   at void Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.   
>      MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:120             
>   at void Spectre.Console.Progress.<>c__DisplayClass32_0`1.<<StartAsync>b__0>d. 
>      MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:138         
>   at async Task<T> Spectre.Console.Internal.DefaultExclusivityMode.RunAsync<T>( 
>      Func<Task<T>> func) in /_/src/Spectre.Console/Internal/                    
>      DefaultExclusivityMode.cs:40                                               
>   at async Task<T> Spectre.Console.Progress.StartAsync<T>(Func<ProgressContext, 
>      Task<T>> action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:121   
>   at async Task<T> Spectre.Console.Status.StartAsync<T>(string status,          
>      Func<StatusContext, Task<T>> func) in /_/src/Spectre.Console/Live/Status/  
>      Status.cs:[11](https://github.com/teodorplop/Nerdvana-Game-Server/actions/runs/9373766145/job/25808267508#step:8:12)7                                                              
>   at async Task Spectre.Console.Status.StartAsync(string status,                
>      Func<StatusContext, Task> action) in /_/src/Spectre.Console/Live/Status/   
>      Status.cs:77                                                               
>   at async Task Unity.Services.Cli.Common.Console.LoadingIndicator.             
>      StartAnsiConsoleStatusAsync(IAnsiConsole console, string description,      
>      Func<StatusContext, Task> callback)                                        
>   at async Task Unity.Services.Cli.Common.Console.LoadingIndicator.             
>      StartLoadingAsync(string description, Func<StatusContext, Task> callback)  
>   at async Task                                                                 
>      Unity.Services.Cli.RemoteConfig.Handlers.ExportImport.ImportHandler.       
>      ImportAsync(ImportInput importInput, RemoteConfigImporter                  
>      remoteConfigImporter, ILoadingIndicator loadingIndicator, CancellationToken
>      cancellationToken)                                                         
>   at async Task<int> System.CommandLine.Invocation.AnonymousCommandHandler.     
>      InvokeAsync(InvocationContext context)                                     
>   at void                                                                       
>      System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<Bui
>      ldInvocationChain>b__0>d.MoveNext()                                        
>   at void                                                                       
>      System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17
>      _0.<<UseParseErrorReporting>b__0>d.MoveNext()                              
>   at void                                                                       
>      System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15
>      _0.<<AddMiddleware>b__0>d.MoveNext()                                       
>   at void                                                                       
>      System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15
>      _0.<<AddMiddleware>b__0>d.MoveNext()                                       
>   at void                                                                       
>      System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15
>      _0.<<AddMiddleware>b__0>d.MoveNext()                                       
>   at void                                                                       
>      System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost
>      >b__0>d.MoveNext()                                                         
>   at void                                                                       
>      System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass[12](https://github.com/teodorplop/Nerdvana-Game-Server/actions/runs/9373766145/job/25808267508#step:8:13)
>      _0.<<UseHelp>b__0>d.MoveNext()                                             
>   at void                                                                       
>      System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22
>      _0.<<UseVersionOption>b__0>d.MoveNext()                                    
>   at void                                                                       
>      System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19
>      _0.<<UseTypoCorrections>b__0>d.MoveNext()                                  
>   at void                                                                       
>      System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDir
>      ective>b__18_0>d.MoveNext()                                                
>   at void                                                                       
>      System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass[16](https://github.com/teodorplop/Nerdvana-Game-Server/actions/runs/9373766145/job/25808267508#step:8:17)
>      _0.<<UseParseDirective>b__0>d.MoveNext()                                   
>   at void                                                                       
>      System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithD
>      otnetSuggest>b__5_0>d.MoveNext()                                           
>   at void                                                                       
>      System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_
>      0.<<UseExceptionHandler>b__0>d.MoveNext()                                  
> Error: Process completed with exit code 2.

**Comment by yoan-bernatchez** [comment]
Hi, we've opened a ticket on our side and are looking into it

We'll update you once a fix is ready

**Comment by GabrielBelmonteUnity** [comment]
Hello!

In the meantime, could you try this instead?
```
mkdir rc_dir
ugs fetch rc_dir -reconcile -s remote-config -e source_env
ugs deploy rc_dir -reconcile -s remote-config -e target_env
```

**Comment by GabrielBelmonteUnity** [comment]
Fix will be in the next release. In the mean time @teodorplop , i recommend you try the alternative above

**Comment by teodorplop** [comment]
@GabrielBelmonteUnity 

Thanks! Will do!

**Comment by teodorplop** [comment]
@GabrielBelmonteUnity 

It does work with the new version. Thank you for the quick fix!

**Comment by GabrielBelmonteUnity** [comment]
@teodorplop 

No problem.
 I strongly recommend you use the recommended method using `fetch` and `deploy`.
Not only is it a legible file you can edit, but you can also deploy it from the editor.

**Comment by teodorplop** [comment]
@GabrielBelmonteUnity 

I'll give that one a try, although I'm using .yml files so that I can easily deploy when pushing or creating branches in git. 

Since you're here, I actually have a question. I noticed that templates are not being exported / imported into the environment. Is this intended?

**Comment by GabrielBelmonteUnity** [comment]
> Since you're here, I actually have a question. I noticed that templates are not being exported / imported into the environment. Is this intended?

They were implemented after, and support has not been ported. I'll poke the RC team.

**Comment by teodorplop** [comment]
Thank you! @GabrielBelmonteUnity
