### ISSUE TITLE
Leaderboard Sorting Always Set to Lowest to Highest

### ISSUE THREAD

**Issue by faridmehrhesam** [Unity-Technologies/unity-gaming-services-cli#8]
Hi team,

I'm attempting to create leaderboards using UGS. However, regardless of the value I set for the **SortOrder**, it always defaults to "Lowest to Highest."
However, when I create a leaderboard through the Unity Cloud Dashboard, the sorting order works as expected.
Am I missing something, or could this be a bug?

**Steps to Reproduce:**

Create a leaderboard using **UGS**.
Attempt to set the **SortOrder** to **"desc"**
Observe that the **SortOrder** is still applied as "Lowest to Highest." in Unity Cloud dashboard.

```json
{
  "$schema": "https://ugs-config-schemas.unity3d.com/v1/leaderboards.schema.json",
  "Id": "DAILY_LEVEL",
  "Name": "Daily Level",
  "SortOrder": "desc",
  "UpdateType": "keepBest",  
  "ResetConfig": {
    "Start": "2025-01-01T00:00:00+00:00",
    "Schedule": "@daily"
  }
}
```

**Expected Behavior:**

The leaderboard should respect the configured **SortOrder** (e.g., "Highest to Lowest").

**Actual Behavior:**

The **SortOrder** always defaults to "Lowest to Highest," regardless of the configuration.

**Environment:**

UGS Version: 1.6.0 and 1.7.0

Let me know if there's additional information I can provide to help resolve this issue.

Thank you!

**Comment by faridmehrhesam** [comment]
Thanks for the quick reply

**Comment by GabrielBelmonteUnity** [comment]
Please try out 1.7.1: https://github.com/Unity-Technologies/unity-gaming-services-cli/releases/
